pwndbg/pwndbg

pwndbg/commands/windbg.py
Allows for easier hexdump access and keeping true with porting windbg commands over to pwndbg
=> Add 'dc' alias for 'hexdump'

pwndbg/commands/search.py, pwndbg/search.py
While searching for `123456` in the the memory using either of `search` or `searchmem` as:
```
pwndbg> search 123456
pwndbg> search '123456'
```
it would convert the 123456 to integer and search for the corresponding hex values in memory. If the user want to search `123456` that was inserted into character array, it was not efficient to use the `search` or `searchmem` with their existing way of working.
Hence, I made this patch to solve this issue by letting the user to input what way he wants to search `123456` as. Hence I added a support for character search in such case which can be fulfilled as:
```
pwndbg> search/c 123456
pwndbg> search/c '123456'
```
Also the support to search directly for hex characters in memory is added in case user wants to search for any arbitrary hex value …
=> Add better features to search and searchmem function by resolving some issues.

pwndbg/auxv.py
The previous code could crash if an entry was malformed or even execute arbitrary python code:
If e.g. the platform string (on the stack) was overwritten with something like " print('pwnd') " (note the whitespace), then gdb would produce the following line:
`15   AT_PLATFORM          String identifying platform    0x7fffffffe8a9 " print('pwnd') "...`
and then parser would `eval("print('pwnd')")` :)
=> Improved auxv entry parsing

setup.sh
Your install instructions say to cd into the top level pwndbg directory and run ./setup.sh. This causes your last popd on line 27 to put you back there, and then line 32 adds an extra /pwndbg/ to the path of gdbinit.py so gdb can't find it on launch.
=> Fix .gdbinit modification line

pwndbg/__init__.py, pwndbg/commands/elfheader.py, pwndbg/commands/vmmap.py
PEDA prints out something similar to `info files` when running elfheader. vmmap is completely different.
=> Made elfheader run `info files`

pwndbg/chain.py, pwndbg/color.py, pwndbg/commands/defcon.py, pwndbg/commands/heap.py
Implemented commands for printing heap chunks and fast bins.
=> Basic implementation of heap commands

pwndbg/commands/context.py
some people really love having as much useful color as possible, therefor introducing a new option to colorize the flags with green/red
```
set colored-flags on
```
=> adding colored-flags config switch to colorize eflags

pwndbg/events
looks like this file was an accident? Can't figure out why it should exist or where this could possibly be used... therefor proposing to delete it :fire:
=> remove seemingly obsolete pwndbg/events file

pwndbg/arch.py, pwndbg/malloc.py, pwndbg/strings.py, pwndbg/ui.py
Minor fix.
I found some of codes contain tab characters. Just replace to 4 space to make coding style consistance.
=> Use 4 space instead of tab

pwndbg/color.py
I make the color of rodata is able to config, and default is normal.
Also, I add missing colorize function `cyan()` so that the other can set the color to cyan() via `pwndbg config`.
=> Add color config of rodata and add cyan() colorize function

pwndbg/disasm/x86.py
Set the target value to `None` for RET instruction which is not PC pointed to.
This fix the disassembly display from:
```
ret     <0>
```
to
```
ret
```
=> Fix resolving the return address on non-PC RET always get 0

pwndbg/disasm/x86.py
I found something strange when I looking at the dump of in `DisassemblyAssistant`.
The following is a exmaple.
```asm
mov rax, qword ptr fs:[0x28]
next = 0x400802
condition = None
operands[0] = CS_OP_REG
str = rax
operands[1] = CS_OP_MEM
str = fs:]
```
You can see `fs:]` is strange, and I found out the `.str` attribute constructor `memory_sz` miss something.
After my patch will get:
```asm
str = [fs:0x28]
```
Here's the other example:
before:
```asm
mov rdx, qword ptr [rbp - 8]
str = rbp - ]
```
after:
```asm
str = [rbp - 8]
```
I don't this patch whether break something because I didn't trace the code to find out who use use the `.str` attribute.
Also, I'm not sure the behavior of origin memory_sz is a design or a bug. If it is a design, please feel free to close this PR.
=> Fix the x86/64 memory_sz name construct process

pwndbg/color.py, pwndbg/commands/context.py, pwndbg/commands/nearpc.py, pwndbg/disasm/color.py
This helps visually distinguish the currently executed instruction and the according source line (if any is available).
=> highlighting the current IP or line of the code/source section

pwndbg/disasm/arch.py, pwndbg/disasm/arm.py, pwndbg/disasm/color.py, pwndbg/disasm/x86.py
As my understanding, `None` is mean "unconditional" and `False` is mean "it is conditional, but will not be taken". So I change the default value of `ins.condition` from `False` to `None` and set the `condition` attribute to `None` for all instructions whose address does not matched PC.
Then we can use `ins.condition` to know whether this condition instruction will be taken or not.
It is useful to show something when a condition instruction will not be taken because there is some instruction like `cmove` which is not a branch instruction. We can't know this instruction will be done or not by the origin UI.
=> Show "x" when the condition instruction will not be taken

pwndbg/disasm/color.py
Show "x" when the condition instruction will not be taken (#74) in commit 6c04e5368e4d48472e10b5fbbb8cbf2a305fe187 introduced a regression because of a typo leading to always show nothing on conditional instructions.
=> fixed condition label expression leading to always be None

pwndbg/config.py
This fixes an issue that can potentially happen with unordered dicts
in python3. A boolean typed config parameter can be handles as
integer dependin on the order of iteration in getParam(value).
The reason for this is because True/False are both, bool and int
at the same time, however its not the other way around.
```
checking type <class 'bool'>
matched True against <class 'bool'>
checking type <class 'str'>
checking type <class 'int'>
matched True against <class 'int'>
In [1]: isinstance(True, bool)
Out[1]: True
In [3]: isinstance(True, int)
Out[3]: True
In [4]: isinstance(1, bool)
Out[4]: False
```
=> fixed potential wrong config param type resolution

pwndbg/__init__.py, pwndbg/commands/misc.py, tests/testLoadsWithoutCrashing.py
Hello,
I have added a possibility to filter the list of commands provided with `pwndbg`, simply by passing an argument to it:
```
pwndbg> pwndbg entry
entry                Set a breakpoint at the first instruction executed in
entry_point          GDBINIT compatibility alias to print the entry point.
pwndbg> 
```
Currently, this is done by simple lowercase string comparison. Imho we don't really need regexes here.
=> Add pwndbg commands list filtering

pwndbg/commands/telescope.py
Sometimes I want to show the stack frame which is already pop, I can only use something like `telescope $sp-0x10`.
I add an argument `offset` of command of `stack` and use `argparse` instead of the origin argument parser. This will be useful. At most of times, I don't want to calculate the actually offset by myself.
```
pwndbg> stack 5 -2
00:0000|      0x7fffffffdc60 <-- 0x13ed
01:0008|      0x7fffffffdc68 --> 0x7ffff7a7d2c8 <-- add    byte ptr [rdi + 0x5f], bl
02:0010| rsp  0x7fffffffdc70 --> 0x7ffff7ff74d0 --> 0x7ffff7a55000 <-- jg     0x7ffff7a55047
03:0018|      0x7fffffffdc78 --> 0x7fffffffdd18 --> 0x4004bf <-- pop    rdi /* '__cxa_atexit' */
04:0020|      0x7fffffffdc80 --> 0x7fffffffdd14 <-- 0x4004bf00000000
```
I put the `count` argument at the first since some people will use …
=> Enhance stack command to support offset argument

pwndbg/commands/search.py
I think `search -t string` behavior was broken by `unicode_literals`. So I fixed to use `b'\x00'` instead of `'\x00'`.
before:
```
pwndbg> search -t string ed
libc-2.19.so    0x7ffff789700c add    byte ptr gs:[rax], al /* u'e' */
libstdc++.so.6.0.19 0x7ffff7b96fc8 add    byte ptr gs:[rax], al /* u'e' */
pwndbg> hexdump 0x7ffff789700c
+0000 0x7ffff789700c  65 00 00 00  64 00 00 00  00 00 00 00  54 00 00 00  |e...|d...|....|T...|
+0010 0x7ffff789701c  68 00 00 00  75 00 00 00  00 00 00 00  46 00 00 00  |h...|u...|....|F...|
+0020 0x7ffff789702c  72 00 00 00  69 00 00 00  00 00 00 00  53 00 00 00  |r...|i...|....|S...|
+0030 0x7ffff789703c  61 00 00 00  74 00 00 00  00 00 00 00  53 00 00 00  |a...|t...|....|S...|
+0040 0x7ffff789704c
```
after:
```
pwndbg> search -t string ed
libc-2.19.so …
```
=> Fix search string as bytes

pwndbg/commands/heap.py
The previous sizes of the fastbins were off by `2 * size_t_size`. This commit fixes that.
I also hardcoded the number of fastbins to 7. On Ubuntu 14.04, this is always true for both 32 bit and 64 bit binaries. I haven't tested on 16.04, but I'd guess it's true there as well. The reason for this change is for some reason, the size of the `fastbinsY` array in glibc is larger than the number of fastbins actually used. Thus, you can allocate and free a chunk of a size you'd expect to see in the fastbin array but you wouldn't see it, which is confusing. Limiting to 7 fastbins prevents this problem. If you think it's better to leave the full number of fastbins even if they're not used, I don't mind taking this out.
=> Fixed fastbin sizes

pwndbg/commands/heap.py
During heap traversal, we'll enter an infinite loop if a 0-sized chunk is found (happens to me frequently while developing exploits), printing the same chunk forever.
=> Avoid infinite loop on 0-sized chunks in heap command

pwndbg/commands/heap.py
Before:
```
pwndbg> heap
Traceback (most recent call last):
File "/opt/pwndbg/pwndbg/commands/__init__.py", line 57, in __call__
return self.function(*args, **kwargs)
File "/opt/pwndbg/pwndbg/commands/__init__.py", line 115, in _OnlyWhenRunning
return function(*a, **kw)
File "/opt/pwndbg/pwndbg/commands/heap.py", line 58, in heap
main_arena = get_main_arena(addr)
File "/opt/pwndbg/pwndbg/commands/heap.py", line 29, in get_main_arena
main_arena = gdb.lookup_symbol('main_arena')[0].value()
AttributeError: 'NoneType' object has no attribute 'value'
```
After:
```
pwndbg> heap
Symbol 'main_arena' not found. Try installing libc debugging symbols or specifying the main arena address and try again
```
=> fix calling value() on NoneType

pwndbg/inthook.py
As I mentioned in #126, I use the future package to make metaclass syntax compatible with both Python 2 and 3.
=> make metaclass syntax in inthook.py compatible with Python 3

pwndbg/__init__.py, pwndbg/color/disasm.py, pwndbg/commands/nearpc.py, pwndbg/commands/telescope.py, pwndbg/commands/theme.py
repr() does not work well when printing unicode sequences (at least in python2)
therefor we add a small switch case in the theme command to properly print
the values depending on their types.
Remove u'' string prefxies as they are superseded by unicode_literals
Fixes #117
=> workaround for python2 unicode printing

pwndbg/commands/context.py, pwndbg/regs.py
Adds an option (show-retaddr-reg) to config to show return address registers like 'lr' on ARM. For #115 
```
show-retaddr-reg       False          whether to show return address register
```
Example:
```
*R0   0xf6fff23c —▸ 0xf66b6454 ◂— 0xe1a00005
*R1   0xf67937c4 —▸ 0x12000 ◂— 0x0
R2   0x0
*R3   0xf6fff23c —▸ 0xf66b6454 ◂— 0xe1a00005
*R4   0x87ed (__libc_csu_init+1) ◂— 0x743f8e9
R5   0x0
*R6   0x856d (_start+1) ◂— lsls   r0, r6, #3
*R7   0xf6fff238 ◂— 0x0
R8   0x0
R9   0x0
*R10  0xf67fdfb4 —▸ 0x2feec ◂— 0x0
R11  0x0
*R12  0xb0
*SP   0xf6fff238 ◂— 0x0
*LR   0x87c9 (main+113) ◂— lsls   r6, r0, #1 /* u'F' */
*PC   0x86b2 (checkpassword+10) ◂— blx    #0x84c4
```
=> add option to show retaddr register to config

pwndbg/commands/context.py
If enabled, this clears the whole screen before printing the context.
This way stepping through the program always starts from the top-left
corner and remains static in its poisition.
Default value: off
=> adding context-clear-screen feature with config value

pwndbg/commands/windbg.py
Tiny fix. Thanks for the tool!
```
pwndbg> dd 0 0
'gdb.Value' object cannot be interpreted as an integer
'dd': Starting at the specified address, dump N dwords
(default 16).
```
=> Fix windbg dX commands with explicit count

pwndbg/strings.py
This now honors unlimited print elements by returning the full string in that case.
=> Fix exception when 'print elements' is unlimited. (Fixes #145)

pwndbg/disasm/__init__.py
This will cause to choose a bad dissassembler so the output (context code) is not shown
=> wrong dissassembler mode choice

pwndbg/disasm/__init__.py
This fixes a regression when the emulator support is disabled via
setting it to None when the import fails. The access happens when
checking if a particular architecture actually supports emulation.
Ensure that emulate has the correct value depending on the availability
of the import and deactivate it otherwise. The following core can safely
rely on the boolean state of the emulate variable.
=> fix NoneType access if emulator not available through import

pwndbg/commands/shell.py
We keep 'find' inside but comment it out so future editors are
aware of why it is missing instead of assuming it was missing
by accident.
=> don't override gdb internal 'find' command via shell cmds

pwndbg/search.py
This will result in an internal exception and make pwndbg stop
searching. Just avoid and exit this search block if the current
search length equals zero.
=> avoid searching 0-length in memory

pwndbg/commands/context.py, pwndbg/commands/nearpc.py, pwndbg/config.py
Adding options so all commands and context lines can be configured independently. For more human friendly behavior of the lines value, we internally divide it by 2 as it functions as a value for before+after current pc.
=> add config for amount of stack, code context and nearpc lines

pwndbg/commands/hexdump.py, pwndbg/commands/misc.py, pwndbg/commands/next.py, pwndbg/commands/search.py, pwndbg/commands/stack.py, pwndbg/commands/xor.py, pwndbg/memory.py, pwndbg/next.py
- more robust and graceful error messages for malformed input
- fix word search by using uniform search type parameter
- graceful error messages on invalid memory regions and invalid count parameters
- only allow retaddr and canary command in running mode
- next commands: check if proc is alive while continuing to avoid exceptions
=> command robustness improvements and graceful errors

pwndbg/disasm/__init__.py
This brings back the functionality to call disasm.one() without
and target address. As a default value the current regs.pc is
selected.
Fix the disasm.near() call to not pass None to disasm.one() when
the backward cache misses, otherwise it wrongly falls back to
the regs.pc value (which near() is not supposed to do in its
context).
=> fix disasm.one() to be called without an address

setup.sh
A few enhancements to setup.sh
- Install `gdb` via `apt-get`
- Ensure that `gdb` is in `$PATH` before attempting to invoke it
- Ensure that the Python has access to `pip` via `ensurepip`
- Upgrade `pip` itself before installing dependencies
- Install dependencies into the correct `site-packages`
- This code was previously removed, but is actually necessary when GDB does not use the system Python
Supersedes #206
=> Enhance setup.sh

pwndbg/typeinfo.py
```c
$ cat kardashian.c
#include "kardashian.h"
struct sample foo;
$ cat kardashian.h
struct sample {
int i;
struct sample *less;
struct sample *more;
};
```
```
pwndbg> ptype foo
No symbol "foo" in current context.
pwndbg> python pwndbg.typeinfo.compile("/home/kim/kardashian.c")
pwndbg> ptype foo
type = struct sample {
int i;
sample *less;
sample *more;
}
```
=> Add ability to load individual symbols

pwndbg/events.py
Added this during debugging mips issue (https://github.com/pwndbg/pwndbg/issues/156).
(note: I've got `set debug-events on`).
```
[dc@dc:challenge]$ gdb ./bender_safe
GNU gdb (GDB) 7.12
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-pc-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For …
```
=> Better exception when calling events

.gitmodules, docs/requirements.txt, requirements.txt, setup.sh
This removes the Git submodules and explicit dependencies on a individual build of Capstone and Unicorn.  This should also greatly simplify the installation process.
=> Use "pip" versions of Capstone and Unicorn

pwndbg/color/disasm.py
If a function name contains the same substring as a branch instruction then those characters are colored as well.
Instead only color the first occurrence of the mnemonic string which should be the actual intended assembly.
=> correct branch coloring

pwndbg/inthook.py
Because of recent changes, the IDA synchronization fails on marshalling a xint instance:
```
$ gdb -q ./babyuse
Pwndbg successfully connected to Ida Pro xmlrpc: http://127.0.0.1:8888
Loaded 108 commands.  Type pwndbg [filter] for a list.
Reading symbols from ./babyuse...(no debugging symbols found)...done.
pwndbg> entry
Temporary breakpoint 1 at 0x56555ca0
Exception during func=pwndbg.ida.Auto_Color_PC (<gdb.BreakpointEvent object at 0x7f1648274468>,)
Traceback (most recent call last):
File "/usr/lib/python3.6/xmlrpc/client.py", line 510, in __dump
f = self.dispatch[type(value)]
KeyError: <class 'pwndbg.inthook.xint'>
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "/home/dc/installed/pwndbg/pwndbg/events.py", line 122, in caller …
```
=> Fix IDA synchronization marshalling xint issue

pwndbg/commands/__init__.py, pwndbg/commands/checksec.py, pwndbg/commands/elf.py, pwndbg/commands/ida.py, pwndbg/commands/misc.py, pwndbg/commands/radare2.py, pwndbg/commands/rop.py, pwndbg/commands/ropper.py, pwndbg/commands/start.py
Introduces `pwndbg.commands.OnlyWithFile` decorator and decorates commands:
* `entry`, `start` - both of them hang pwndbg when there was no file loaded in gdb: https://asciinema.org/a/d5tyb7ombf18ppb3zwomcwjo9
* `rop`, `ropp`, `ropper`
* `elfheader`, `elf`, `gotplt`, `plt`
* `r2`
* `errno`
Also removes redundant imports and refactors the files a little bit (mainly newlines).
=> Fix commands without file loaded in gdb

pwndbg/__init__.py, pwndbg/commands/version.py, pwndbg/prompt.py, pwndbg/version.py
This adds pwndbg's git commit id to pwndbg banner.
This might be handy for future bug reports as there were cases when someone had out-of-date pwndbg version and/or didn't report pwndbg version.
=> Add version command
